services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data  # Mount the persistent volume for Elasticsearch data

volumes:
  esdata01:  # Create a named volume for Elasticsearch data
    driver: local
